version: "3"
services:
  scripts:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ao3-scripts
    volumes:
      - ./:/srv/otw
    ports:
      - "8081:80"
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: "3"
    tty: true